<?php
// Generic error page. Preserve the actual HTTP status when possible.
$status = http_response_code();
if (!$status || $status < 400) $status = 500;
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Something Broke — <?php echo htmlspecialchars((string)$status); ?></title>
<style>
:root{--bg:#f4f7fb;--card:#fff;--ink:#121826;--muted:#667085;--accent:#0f6b78;--soft:#e3f3f5;--border:#dce5e8}*{box-sizing:border-box}body{margin:0;min-height:100vh;padding:22px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#eef9fa,#f8fafc);font-family:Inter,system-ui,sans-serif;color:var(--ink)}.card{width:min(980px,100%);background:#ffffffeb;border:1px solid var(--border);border-radius:32px;padding:clamp(28px,6vw,62px);box-shadow:0 25px 80px #102a3312;display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center}.logo{width:145px;margin-bottom:34px}.logo img{width:100%;height:auto}.status{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;background:var(--soft);color:var(--accent);font-size:12px;font-weight:900;letter-spacing:.08em}.dot{width:8px;height:8px;border-radius:50%;background:currentColor;animation:blink 1.2s infinite}h1{font-size:clamp(34px,6vw,62px);line-height:.98;letter-spacing:-.05em;margin:18px 0}p{font-size:17px;line-height:1.65;color:var(--muted);margin:0 0 15px;max-width:600px}.sarcastic{font-weight:800;color:var(--ink)}.buttons{display:flex;flex-wrap:wrap;gap:12px;margin-top:26px}.btn{border:0;border-radius:14px;padding:13px 18px;font-weight:800;text-decoration:none;cursor:pointer;transition:.2s}.primary{background:var(--accent);color:#fff}.secondary{background:var(--soft);color:var(--accent)}.btn:hover{transform:translateY(-3px);box-shadow:0 10px 24px #0f6b7822}.visual{text-align:center}.mascot{width:min(330px,72vw);max-width:100%;cursor:pointer;transition:.3s;filter:drop-shadow(0 20px 20px #0f3d451c)}.mascot:hover{transform:translateY(-10px) rotate(3deg)}.hint{font-size:12px;color:#98a2b3;margin-top:8px}.footer{margin-top:24px;font-size:12px;color:#98a2b3}.wiggle{animation:wiggle .55s ease}@keyframes blink{50%{opacity:.25}}@keyframes wiggle{20%{transform:rotate(-7deg)}40%{transform:rotate(7deg)}60%{transform:rotate(-5deg)}80%{transform:rotate(5deg)}}@media(max-width:720px){body{padding:12px}.card{grid-template-columns:1fr;text-align:center;border-radius:24px}.logo{margin:0 auto 25px}.visual{order:-1}.mascot{width:min(260px,62vw)}.buttons{justify-content:center}}
</style></head><body><main class="card"><section><div class="logo"><img src="/Assets/logo.png" alt="Logo"></div><div class="status"><span class="dot"></span> ERROR <?php echo htmlspecialchars((string)$status); ?></div><h1>Something went spectacularly wrong.</h1><p>The server tried. You tried. Somewhere between those two events, reality filed a complaint.</p><p class="sarcastic">Please try again. Preferably after giving the internet a tiny moment to reconsider its life choices.</p><div class="buttons"><a class="btn primary" href="/">Return home</a><button class="btn secondary" id="retry">Try again</button></div><div class="footer">Error <?php echo htmlspecialchars((string)$status); ?> • We have absolutely no idea what happened. But we are looking into it.</div></section><section class="visual"><img class="mascot" id="mascot" src="/Assets/mascot.png" alt="Mascot"><div class="hint">Click the mascot. It knows nothing, but it may look concerned.</div></section></main><script>
const mascot=document.getElementById('mascot'),retry=document.getElementById('retry');retry.onclick=()=>{retry.textContent='Retrying…';setTimeout(()=>location.reload(),450)};mascot.onclick=()=>{mascot.classList.remove('wiggle');void mascot.offsetWidth;mascot.classList.add('wiggle')};
</script></body></html>
