<?php
http_response_code(403);
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Nope — Admin</title>
<style>
:root{--bg:#f7f8fc;--card:#fff;--ink:#111827;--muted:#667085;--accent:#7c3aed;--soft:#f0e9ff;--border:#e5e7eb}*{box-sizing:border-box}body{margin:0;min-height:100vh;padding:24px;display:grid;place-items:center;background:radial-gradient(circle at 80% 20%,#eadfff,transparent 30%),var(--bg);font-family:Inter,system-ui,sans-serif;color:var(--ink)}.wrap{width:min(900px,100%)}.card{background:var(--card);border:1px solid var(--border);border-radius:30px;padding:clamp(28px,6vw,60px);text-align:center;box-shadow:0 25px 80px #1f123c12;position:relative;overflow:hidden}.logo{width:140px;max-width:45%;margin:0 auto 24px}.logo img{width:100%;height:auto}.lock{font-size:clamp(70px,13vw,130px);line-height:1;margin:5px 0 12px;animation:pulse 2.5s infinite}h1{font-size:clamp(32px,6vw,58px);letter-spacing:-.045em;margin:0 0 15px}p{font-size:17px;line-height:1.65;color:var(--muted);max-width:650px;margin:0 auto 24px}.sarcastic{font-weight:800;color:var(--ink)}.actions{display:flex;justify-content:center;flex-wrap:wrap;gap:12px}.btn{border:0;border-radius:14px;padding:13px 19px;text-decoration:none;font-weight:800;cursor:pointer;transition:.2s}.primary{background:var(--accent);color:#fff}.secondary{background:var(--soft);color:var(--accent)}.btn:hover{transform:translateY(-3px);box-shadow:0 12px 25px #7c3aed22}.mascot{width:min(250px,62vw);margin:30px auto 0;display:block;cursor:pointer;transition:.25s}.mascot:hover{transform:scale(1.05) rotate(2deg)}.tag{margin-top:20px;font-size:12px;color:#98a2b3}.denied{animation:denied .45s ease}@keyframes denied{25%{transform:translateX(-8px)}50%{transform:translateX(8px)}75%{transform:translateX(-4px)}}@keyframes pulse{50%{transform:scale(1.05)}}
</style></head><body><main class="wrap"><section class="card"><div class="logo"><img src="/Assets/logo.png" alt="Logo"></div><div class="lock" id="lock">🔒</div><h1>Nice try, Sherlock.</h1><p>You found the admin entrance. Unfortunately, finding the door does not mean we are handing you the keys.</p><p class="sarcastic">The server has respectfully declined your invitation to become an administrator.</p><div class="actions"><a class="btn primary" href="/">I'll behave</a><button class="btn secondary" id="annoy">Ask again</button></div><img class="mascot" id="mascot" src="/Assets/mascot.png" alt="Mascot"><div class="tag">403 • Access denied • Ego denied • Nice attempt</div></section></main><script>
const lock=document.getElementById('lock'),mascot=document.getElementById('mascot'),annoy=document.getElementById('annoy');annoy.onclick=()=>{lock.classList.remove('denied');void lock.offsetWidth;lock.classList.add('denied');annoy.textContent='Still no';};mascot.onclick=()=>{mascot.style.transform='rotate(-8deg) scale(1.08)';setTimeout(()=>mascot.style.transform='',400)};
</script></body></html>
